/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Path to the VaM installation folder.
 */
export type VaMInstallationFolder = string;
/**
 * Application environment.
 */
export type ApplicationEnvironment = "production" | "development" | "test";
/**
 * Current application version.
 */
export type ApplicationVersion = string;
/**
 * Logging detail level. Changes take effect on next start.
 */
export type LogLevel = 0 | 1 | 2 | 3;
/**
 * Path where application data is stored.
 */
export type ApplicationStoragePath = string;
/**
 * Window height in pixels.
 */
export type WindowHeight = number;
/**
 * Window width in pixels.
 */
export type WindowWidth = number;
/**
 * Window x-position on screen.
 */
export type WindowXPosition = Position | number;
export type Position = "center" | "start" | "end";
/**
 * Window y-position on screen.
 */
export type WindowYPosition = Position | number;

export interface ConfigSchema {
  "vam.path"?: VaMInstallationFolder;
  "app.env": ApplicationEnvironment;
  "app.version": ApplicationVersion;
  "log.level": LogLevel;
  "data.path": ApplicationStoragePath;
  "window.height": WindowHeight;
  "window.width": WindowWidth;
  "window.x": WindowXPosition;
  "window.y": WindowYPosition;
}
