/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The environment in which the application is running.
 */
export type ApplicationEnvironment = "production" | "development" | "test";
/**
 * The language code for the application's user interface.
 */
export type ApplicationLanguage = string;
/**
 * The current version of the application.
 */
export type ApplicationVersion = string;
/**
 * The level of logging detail to be recorded by the application.
 */
export type LoggingLevel = 0 | 1 | 2 | 3;
/**
 * The file system path where application data is stored.
 */
export type UserdataStoragePath = string;
/**
 * The height of the application window in pixels.
 */
export type WindowHeight = number;
/**
 * The width of the application window in pixels.
 */
export type WindowWidth = number;
/**
 * The x-coordinate of the application window's position on the screen.
 */
export type WindowXPosition = Position | number;
export type Position = "center" | "start" | "end";
/**
 * The y-coordinate of the application window's position on the screen.
 */
export type WindowYPosition = Position | number;

export interface ConfigSchema {
  "app.env": ApplicationEnvironment;
  "app.language": ApplicationLanguage;
  "app.version": ApplicationVersion;
  "log.level": LoggingLevel;
  "data.path": UserdataStoragePath;
  "window.height": WindowHeight;
  "window.width": WindowWidth;
  "window.x": WindowXPosition;
  "window.y": WindowYPosition;
}
