/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export default interface ConfigSchema {
  'db.url': string
  'library.url': string
  'logs.url': string
  'logs.file.level': 'error' | 'warn' | 'info' | 'verbose' | 'debug'
  'logs.console.level': 'error' | 'warn' | 'info' | 'verbose' | 'debug'
  'vam.url'?: string
  'images.url': string
  'images.quality': number
  'user.name': string
  'user.avatar'?: string
}
