enum AssetType {
  AddonPackage = 'addon_package',
  AnimationPreset = 'animation_preset',
  AppearancePreset = 'appearance_preset',
  AssetBundle = 'asset_bundle',
  BreastPreset = 'breast_preset',
  Clothing = 'clothing',
  ClothingPreset = 'clothing_preset',
  GeneralPreset = 'general_preset',
  GlutePreset = 'glute_preset',
  Hair = 'hair',
  HairPreset = 'hair_preset',
  Morph = 'morph',
  MorphPreset = 'morph_preset',
  PluginPreset = 'plugin_preset',
  PosePreset = 'pose_preset',
  Scene = 'scene',
  Script = 'script',
  ScriptPreset = 'script_preset',
  SkinPreset = 'skin_preset',
  Subscene = 'subscene',
  Texture = 'texture',
}

export const AssetTypeDisplayNameMap = {
  [AssetType.AddonPackage]: 'Addon Package',
  [AssetType.AnimationPreset]: 'Animation Preset',
  [AssetType.AppearancePreset]: 'Appearance Preset',
  [AssetType.AssetBundle]: 'Asset Bundle',
  [AssetType.BreastPreset]: 'Breast Preset',
  [AssetType.Clothing]: 'Clothing',
  [AssetType.ClothingPreset]: 'Clothing Preset',
  [AssetType.GeneralPreset]: 'General Preset',
  [AssetType.GlutePreset]: 'Glute Preset',
  [AssetType.Hair]: 'Hair',
  [AssetType.HairPreset]: 'Hair Preset',
  [AssetType.Morph]: 'Morph',
  [AssetType.MorphPreset]: 'Morph Preset',
  [AssetType.PluginPreset]: 'Plugin Preset',
  [AssetType.PosePreset]: 'Pose Preset',
  [AssetType.Scene]: 'Scene',
  [AssetType.Script]: 'Script',
  [AssetType.ScriptPreset]: 'Script Preset',
  [AssetType.SkinPreset]: 'Skin Preset',
  [AssetType.Subscene]: 'Subscene',
  [AssetType.Texture]: 'Texture',
}

export default AssetType
